version: "3"

services:
  api:
    build: "./api"
    networks:
      - gateway
    ports:
      - "5042:5042"
    volumes:
      - ./api/db:/opt/api/db
  app:
    build: "./frontend"
    depends_on:
      - webserver
    networks:
      - gateway
    tty: true
    volumes:
      - static-content1:/opt/app/gramps
  webserver:
    build: "./webserver"
    networks:
      - gateway
    ports:
      - "80:80"
    volumes:
      - static-content1:/opt/app/gramps
networks:
  gateway: {}
volumes:
  static-content1: {}
